name: pull request - check types

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check_types:
    name: Check types
    uses: ./.github/workflows/check_types.yml
    secrets: inherit
