name: Update Dependencies

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 */10 * *" # every 10 days

jobs:
  update-dependencies:
    name: Update Dependencies
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11"]
        poetry-version: ["latest"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
          poetry self add poetry-plugin-up

      - name: Update dependencies
        run: poetry up --latest

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.UPDATE_DEPENDENCIES_BOT_TOKEN }}
          base: master
          branch: gh-action-bot/update-dependencies
          title: "Update dependencies"
          body: "This PR updates dependencies to their latest versions."
          draft: false
